.TH keysid 8 "October 2005"
.SH NAME
keysid \- keys intercepting daemon
.SH SYNOPSIS
.B keysid
[\fIconfig_file\fR]
.SH DESCRIPTION
keysid is a highly configurable linux daemon which lets you intercept
keyboard key press and make them execute the programs you want.
It's thought for laptop and multimedia keyboards, which usually have
more keys than standard keyboards, but it works with all the keys.
.SH KNOWN BUGS
You shouldn't press any key for a couple of milliseconds after you start
the program, otherwise it couldn't get your input in the right way.
.SH SEE ALSO
keyscfg(8)
.SH AUTHOR
.na
.nf
Daniele Sempione <scrows at oziosi.org>
